// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abphxdosqwzvsueehvir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFicGh4ZG9zcXd6dnN1ZWVodmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjcwOTMsImV4cCI6MjA2MjIwMzA5M30.N2PdZAt-xnvEuMzwpAXWFEb0XcHRW2TG_58Kko_blzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);